INSERT INTO DesignOfPlateSeal(DesignOfSeal, PressurePNFrom, PressurePNTo, DiametrDNFrom, DiametrDNTo, MaterialOfSeal) VALUES (N'соединительный выступ - соединительный выступ', 1, 2.5, 10, 3000, N'паронит')
INSERT INTO DesignOfPlateSeal(DesignOfSeal, PressurePNFrom, PressurePNTo, DiametrDNFrom, DiametrDNTo, MaterialOfSeal) VALUES (N'соединительный выступ - соединительный выступ', 2.5, 6.3, 10, 2400, N'паронит')
INSERT INTO DesignOfPlateSeal(DesignOfSeal, PressurePNFrom, PressurePNTo, DiametrDNFrom, DiametrDNTo, MaterialOfSeal) VALUES (N'соединительный выступ - соединительный выступ', 6.3, 10, 10, 2000, N'паронит')
INSERT INTO DesignOfPlateSeal(DesignOfSeal, PressurePNFrom, PressurePNTo, DiametrDNFrom, DiametrDNTo, MaterialOfSeal) VALUES (N'соединительный выступ - соединительный выступ', 10, 16, 10, 1600, N'паронит')
INSERT INTO DesignOfPlateSeal(DesignOfSeal, PressurePNFrom, PressurePNTo, DiametrDNFrom, DiametrDNTo, MaterialOfSeal) VALUES (N'соединительный выступ - соединительный выступ', 16, 25, 10, 1400, N'паронит')
INSERT INTO DesignOfPlateSeal(DesignOfSeal, PressurePNFrom, PressurePNTo, DiametrDNFrom, DiametrDNTo, MaterialOfSeal) VALUES (N'выступ - впадина', 1, 40, 10, 800, N'паронит')
INSERT INTO DesignOfPlateSeal(DesignOfSeal, PressurePNFrom, PressurePNTo, DiametrDNFrom, DiametrDNTo, MaterialOfSeal) VALUES (N'шип - паз', 1, 40, 10, 800, N'паронит')
INSERT INTO DesignOfPlateSeal(DesignOfSeal, PressurePNFrom, PressurePNTo, DiametrDNFrom, DiametrDNTo, MaterialOfSeal) VALUES (N'плоскость', 1, 2.5, 10, 3000, N'паронит')
INSERT INTO DesignOfPlateSeal(DesignOfSeal, PressurePNFrom, PressurePNTo, DiametrDNFrom, DiametrDNTo, MaterialOfSeal) VALUES (N'плоскость', 2.5, 6.0, 10, 2400, N'паронит')
