INSERT INTO EnvironmentTable (Environment, Pressure, Execution) VALUES (N'Трудногорючие и негорючие (непожаровзрывоопасные) вещества', 6, N'плоскость')
INSERT INTO EnvironmentTable (Environment, Pressure, Execution) VALUES (N'Трудногорючие и негорючие (непожаровзрывоопасные) вещества', 25, N'соединительный выступ')
INSERT INTO EnvironmentTable (Environment, Pressure, Execution) VALUES (N'Вредные вещества 4-го класса опасности (малоопасные)', 16, N'соединительный выступ')
INSERT INTO EnvironmentTable (Environment, Pressure, Execution) VALUES (N'Вредные вещества 4-го класса опасности (малоопасные)', 25, N'выступ - впадина')
INSERT INTO EnvironmentTable (Environment, Pressure, Execution) VALUES (N'Вредные вещества 4-го класса опасности (малоопасные)', 25, N'шип - паз')
INSERT INTO EnvironmentTable (Environment, Pressure, Execution) VALUES (N'Вредные вещества 1, 2 и 3 классов опасности (высокоопасные и умеренно опасные)', 40, N'соединительный выступ')
INSERT INTO EnvironmentTable (Environment, Pressure, Execution) VALUES (N'Пожаровзрывоопасные вещества (горючие газы и жидкости, легковоспламеняющиеся жидкости)', 250, N'выступ - впадина')
INSERT INTO EnvironmentTable (Environment, Pressure, Execution) VALUES (N'Пожаровзрывоопасные вещества (горючие газы и жидкости, легковоспламеняющиеся жидкости)', 250, N'шип - паз')
INSERT INTO EnvironmentTable (Environment, Pressure, Execution) VALUES (N'Вредные вещества 1-го класса опасности (чрезвычайно опасные)', 250, N'выступ - впадина')
INSERT INTO EnvironmentTable (Environment, Pressure, Execution) VALUES (N'Вредные вещества 1-го класса опасности (чрезвычайно опасные)', 250, N'шип - паз')
INSERT INTO EnvironmentTable (Environment, Pressure, Execution) VALUES (N'ВОТ (высокотемпературный органический теплоноситель)', 250, N'шип - паз')
INSERT INTO EnvironmentTable (Environment, Pressure, Execution) VALUES (N'Фреон, аммиак, водород', 250, N'выступ - впадина')
INSERT INTO EnvironmentTable (Environment, Pressure, Execution) VALUES (N'Фреон, аммиак, водород', 250, N'шип - паз')
