INSERT INTO TypeAndMaterialOfSeal(Type_seal, Material, Coef_m, q_obzh, q, K_obzh) VALUES (N'Плоская неметаллическая', N'резина по ГОСТ 7338 с твердостью по Шору А до 65 единиц', 0.5, 2.0, 18.0, 0.04)
INSERT INTO TypeAndMaterialOfSeal(Type_seal, Material, Coef_m, q_obzh, q, K_obzh) VALUES (N'Плоская неметаллическая', N'резина по ГОСТ 7338 с твердостью по Шору А более 65 единиц', 1.0, 4.0, 20.0, 0.09)
INSERT INTO TypeAndMaterialOfSeal(Type_seal, Material, Coef_m, q_obzh, q, K_obzh, E_p) VALUES (N'Плоская неметаллическая', N'паронит по ГОСТ 481', 2.5, 20.0, 130.0, 0.9, 0.02)
INSERT INTO TypeAndMaterialOfSeal(Type_seal, Material, Coef_m, q_obzh, q, K_obzh, E_p) VALUES (N'Плоская неметаллическая', N'картон асбестовый по ГОСТ 2850', 2.5, 20.0, 130.0, 0.9, 0.02)
INSERT INTO TypeAndMaterialOfSeal(Type_seal, Material, Coef_m, q_obzh, q, K_obzh, E_p) VALUES (N'Плоская неметаллическая', N'фторопласт 4', 2.5, 10.0, 40.0, 1.0, 0.02)
INSERT INTO TypeAndMaterialOfSeal(Type_seal, Material, Coef_m, q_obzh, q, K_obzh, E_p, with_circles) VALUES (N'Плоская неметаллическая', N'терморасширенный графитовый материал (типа "Графлекс")', 2.0, 4.0, 200.0, 1.0, 0.02, 1)
INSERT INTO TypeAndMaterialOfSeal(Type_seal, Material, Coef_m, q_obzh, q, K_obzh, E_p, with_circles, h_seal) VALUES (N'Плоская неметаллическая', N'терморасширенный графитовый материал (типа "Графлекс")', 2.5, 4.0, 120.0, 1.0, 0.02, 0, 2)
INSERT INTO TypeAndMaterialOfSeal(Type_seal, Material, Coef_m, q_obzh, q, K_obzh, E_p, with_circles, h_seal) VALUES (N'Плоская неметаллическая', N'терморасширенный графитовый материал (типа "Графлекс")', 2.5, 4.0, 100.0, 1.0, 0.02, 0, 3)
INSERT INTO TypeAndMaterialOfSeal(Type_seal, Material, Coef_m, q_obzh) VALUES (N'Плоская спирально-навитая', N'с лентой из нержавеющей стали', 3.0, 69.0)
INSERT INTO TypeAndMaterialOfSeal(Type_seal, Material, Coef_m, q_obzh) VALUES (N'Плоская спирально-навитая', N'с лентой из углеродистой стали', 2.5, 69.0)
